import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";

import { createClient } from "@hey-api/openapi-ts";

const require = createRequire(import.meta.url);

const packageRoot = path.resolve(import.meta.dirname, "..");
const openapiPath = path.resolve(packageRoot, "openapi", "openapi.yaml");
const generatedDir = path.resolve(packageRoot, "generated");
const outputDir = path.resolve(generatedDir, "_client");
const wrapperPath = path.resolve(generatedDir, "client.ts");
const openapiTsPackagePath = require.resolve(
  "@hey-api/openapi-ts/package.json",
);
const bundledClientsDir = path.resolve(
  path.dirname(openapiTsPackagePath),
  "dist",
  "clients",
);

const contractBanner = [
  "// This file is auto-generated from the OpenAPI contract.",
  'export * from "./_client/index.js";',
  "",
].join("\n");

const generatedHeader = "// This file is auto-generated by @hey-api/openapi-ts";

const bundleLayouts = [
  {
    sourceDir: path.resolve(bundledClientsDir, "core"),
    targetDir: path.resolve(outputDir, "core"),
  },
  {
    sourceDir: path.resolve(bundledClientsDir, "fetch"),
    targetDir: path.resolve(outputDir, "client"),
  },
];

const toBundledPath = (relativePath) => {
  const extension = path.extname(relativePath);
  const name = path.basename(relativePath, extension);

  if (name === "index") {
    return relativePath;
  }

  return path.join(path.dirname(relativePath), `${name}.gen${extension}`);
};

const rewriteBundledImports = (source) => {
  const rewrittenImports = source.replace(
    /(from\s+['"])(\.{1,2}\/[^'"]+)(['"])/g,
    (_match, prefix, importPath, suffix) => {
      const parsed = path.posix.parse(importPath);
      const rewrittenBase =
        parsed.name === "index" ? parsed.base : `${parsed.name}.gen.js`;
      const rewrittenPath = parsed.dir
        ? `${parsed.dir}/${rewrittenBase}`
        : `./${rewrittenBase}`;
      return `${prefix}${rewrittenPath}${suffix}`;
    },
  );

  return rewrittenImports
    .replace(
      "value.forEach((v) => serializeFormDataPair(data, key, v));",
      "value.forEach((v) => {\n          serializeFormDataPair(data, key, v);\n        });",
    )
    .replace(
      "value.forEach((v) => serializeUrlSearchParamsPair(data, key, v));",
      "value.forEach((v) => {\n          serializeUrlSearchParamsPair(data, key, v);\n        });",
    );
};

const copyBundledDirectory = async ({ sourceDir, targetDir }) => {
  await mkdir(targetDir, { recursive: true });

  for (const entry of await readdir(sourceDir, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDir, entry.name);
    const targetPath = path.join(targetDir, toBundledPath(entry.name));

    if (entry.isDirectory()) {
      await copyBundledDirectory({
        sourceDir: sourcePath,
        targetDir: targetPath,
      });
      continue;
    }

    const content = await readFile(sourcePath, "utf8");
    const rewritten = rewriteBundledImports(content);
    await writeFile(targetPath, `${generatedHeader}\n\n${rewritten}\n`, "utf8");
  }
};

const rewriteGeneratedImports = async (filePath) => {
  const content = await readFile(filePath, "utf8");
  const rewritten = content.replaceAll(
    "@hey-api/client-fetch",
    "./client/index.js",
  );
  await writeFile(filePath, rewritten, "utf8");
};

await mkdir(generatedDir, { recursive: true });
await rm(outputDir, { force: true, recursive: true });

await createClient({
  input: openapiPath,
  output: outputDir,
  plugins: [
    "@hey-api/typescript",
    { name: "@hey-api/sdk", client: "@hey-api/client-fetch" },
    { name: "@hey-api/client-fetch", bundle: false },
  ],
});

for (const layout of bundleLayouts) {
  await copyBundledDirectory(layout);
}

await rewriteGeneratedImports(path.resolve(outputDir, "client.gen.ts"));
await rewriteGeneratedImports(path.resolve(outputDir, "sdk.gen.ts"));
await writeFile(wrapperPath, contractBanner, "utf8");
